### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by mohannadjamal** [rdkcentral/Thunder#1212]
I am currently trying to build and install this package and I am currently facing an issue when trying to build and install it. I am using Ubuntu 22.04.1 LTS.
```
CMake Error at cmake/common/CmakeHelperFunctions.cmake:152 (message):
  WPEFrameworkPlugins wants WPEFrameworkMessaging::WPEFrameworkMessaging is
  assumed to be known cmake Target, but it's not known in this scope, maybe
  you forgot a find_package
Call Stack (most recent call first):
  cmake/common/CmakeHelperFunctions.cmake:583 (get_if_link_libraries)
  Source/plugins/CMakeLists.txt:157 (InstallPackageConfig)
```
Thank you.

**Comment by pwielders** [comment]
This is due to the missing flag: MESSAGING. As of R4, we nolonger support TRACING, that has been replaced by MESSAGING. A JIRA ticket is raised to make this the default on R$, but untill that time, you need to forcefully select it (See: https://github.com/rdkcentral/Thunder/blob/master/Source/CMakeLists.txt#L90) so pass -DMESSAGING and remove (if set) -DTRACING

**Comment by mohannadjamal** [comment]
Okay thank you, I will try and see
